### ISSUE TITLE
Error [ERR_REQUIRE_ESM] at require("nanoid") in conf.js

### ISSUE THREAD

**Issue by SureshKarthik** [IoTKETI/nCube-Thyme-Nodejs#4]
https://github.com/IoTKETI/nCube-Thyme-Nodejs/blob/e377ba1c2f12e46b4f02d709cd7cf8d31a8225dd/conf.js#L16

>node thyme.js
nCube-Thyme-Nodejs\conf.js:16
var nanoid = require("nanoid");
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module nCube-Thyme-Nodejs\node_modules\nanoid\index.js from nCube-Thyme-Nodejs\conf.js not supported.
Instead change the require of index.js in nCube-Thyme-Nodejs\conf.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (nCube-Thyme-Nodejs\conf.js:16:14)
    at Object.<anonymous> (nCube-Thyme-Nodejs\thyme.js:20:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.12.1

**Comment by SureshKarthik** [comment]
Same issue is observed in latest stable Node.js v18.15.0
